<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260526154321 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout champ est_agregateur dans scraping_sources + table suggested_sources (découverte automatique de sources)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE suggested_sources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_organisme VARCHAR(255) NOT NULL, url VARCHAR(500) DEFAULT NULL, type_pressenti VARCHAR(50) DEFAULT NULL, pays_zone VARCHAR(100) DEFAULT NULL, discipline_pressentie VARCHAR(200) DEFAULT NULL, raison_suggestion TEXT DEFAULT NULL, origine VARCHAR(50) NOT NULL, statut VARCHAR(20) NOT NULL, source_origine VARCHAR(500) NOT NULL, date_decouverte TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        // Index sur url : utilisé par existsByUrl() à chaque candidat LLM (potentiellement 20× par agrégateur)
        $this->addSql('CREATE INDEX idx_suggested_sources_url ON suggested_sources (url)');
        // Index sur statut : utilisé par findAllByStatut() et countByStatut() à chaque chargement admin
        $this->addSql('CREATE INDEX idx_suggested_sources_statut ON suggested_sources (statut)');
        $this->addSql('ALTER TABLE scraping_sources ADD est_agregateur BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE scraping_sources ALTER nb_items_dernier_run DROP DEFAULT');
        $this->addSql('ALTER TABLE scraping_sources ALTER statut_dernier_run DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_suggested_sources_url');
        $this->addSql('DROP INDEX idx_suggested_sources_statut');
        $this->addSql('DROP TABLE suggested_sources');
        $this->addSql('ALTER TABLE scraping_sources DROP est_agregateur');
        $this->addSql('ALTER TABLE scraping_sources ALTER nb_items_dernier_run SET DEFAULT 0');
        $this->addSql('ALTER TABLE scraping_sources ALTER statut_dernier_run SET DEFAULT \'never_run\'');
    }
}
