<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration : Création de la table creator_payout_profiles (ADR-0027, Lot 1).
 *
 * Cette table stocke les coordonnées de versement des créateurs (IBAN, BIC, SIRET,
 * nom du titulaire, pièce d'identité) pour le paiement manuel par virement après ateliers.
 *
 * SÉCURITÉ & RGPD :
 *   - identity_document_path : chemin RELATIF vers le fichier stocké HORS public/ (var/secure_uploads/).
 *     Ce n'est PAS une URL publique — l'accès se fait uniquement via AdminCreatorPayoutController.
 *   - onDelete CASCADE (user_id) : si le compte est supprimé (RGPD), le profil l'est aussi.
 *   - onDelete SET NULL (verified_by_id) : on conserve l'historique si l'admin est supprimé.
 *
 * Index créés :
 *   - UNIQ_575B110EA76ED395 : user_id (OneToOne — un seul profil par utilisateur)
 *   - IDX_575B110E69F4B775  : verified_by_id (FK vers users)
 */
final class Version20260623130004 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création de creator_payout_profiles pour les coordonnées de versement créateur (ADR-0027, Lot 1) : IBAN, BIC, SIRET, pièce d\'identité sécurisée, statut de vérification admin.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE creator_payout_profiles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, iban VARCHAR(34) NOT NULL, bic VARCHAR(11) DEFAULT NULL, siret VARCHAR(14) NOT NULL, account_holder_name VARCHAR(255) NOT NULL, identity_document_path VARCHAR(255) DEFAULT NULL, identity_document_original_name VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, rejection_reason TEXT DEFAULT NULL, verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, verified_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_575B110EA76ED395 ON creator_payout_profiles (user_id)');
        $this->addSql('CREATE INDEX IDX_575B110E69F4B775 ON creator_payout_profiles (verified_by_id)');
        $this->addSql('ALTER TABLE creator_payout_profiles ADD CONSTRAINT FK_575B110EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE creator_payout_profiles ADD CONSTRAINT FK_575B110E69F4B775 FOREIGN KEY (verified_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE creator_payout_profiles DROP CONSTRAINT FK_575B110EA76ED395');
        $this->addSql('ALTER TABLE creator_payout_profiles DROP CONSTRAINT FK_575B110E69F4B775');
        $this->addSql('DROP TABLE creator_payout_profiles');
    }
}
