<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * ADR-0038 — Fiches « Nos associations » (BazaArt Guadeloupe, BazaArt Paris).
 *
 * Une fiche par association : identité (recopiée dans les candidatures) et
 * critères qui affinent le tri des opportunités (territoire, thèmes, mots à
 * exclure, types recherchés, disciplines).
 *
 * Pas de données insérées ici : les deux fiches sont créées, pré-remplies, à la
 * première ouverture de l'onglet « Opportunités » (AssociationProfileService).
 */
final class Version20260930160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'ADR-0038 : fiches des associations (project_association_profiles + disciplines).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE project_association_profiles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, association VARCHAR(20) NOT NULL, mission TEXT DEFAULT NULL, publics TEXT DEFAULT NULL, activities TEXT DEFAULT NULL, siret VARCHAR(20) DEFAULT NULL, founded_year INT DEFAULT NULL, annual_budget VARCHAR(100) DEFAULT NULL, team VARCHAR(255) DEFAULT NULL, website_url VARCHAR(255) DEFAULT NULL, territory_keywords TEXT DEFAULT NULL, theme_keywords TEXT DEFAULT NULL, excluded_keywords TEXT DEFAULT NULL, sought_types JSON NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B1EAEF9FD8521CC ON project_association_profiles (association)');
        $this->addSql('CREATE INDEX IDX_9B1EAEF9896DBBDE ON project_association_profiles (updated_by_id)');
        $this->addSql('CREATE TABLE project_association_profile_disciplines (association_profile_id INT NOT NULL, discipline_id INT NOT NULL, PRIMARY KEY (association_profile_id, discipline_id))');
        $this->addSql('CREATE INDEX IDX_E3D1986EEC317002 ON project_association_profile_disciplines (association_profile_id)');
        $this->addSql('CREATE INDEX IDX_E3D1986EA5522701 ON project_association_profile_disciplines (discipline_id)');
        $this->addSql('ALTER TABLE project_association_profiles ADD CONSTRAINT FK_9B1EAEF9896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_association_profile_disciplines ADD CONSTRAINT FK_E3D1986EEC317002 FOREIGN KEY (association_profile_id) REFERENCES project_association_profiles (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_association_profile_disciplines ADD CONSTRAINT FK_E3D1986EA5522701 FOREIGN KEY (discipline_id) REFERENCES disciplines (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_association_profile_disciplines DROP CONSTRAINT FK_E3D1986EEC317002');
        $this->addSql('ALTER TABLE project_association_profile_disciplines DROP CONSTRAINT FK_E3D1986EA5522701');
        $this->addSql('ALTER TABLE project_association_profiles DROP CONSTRAINT FK_9B1EAEF9896DBBDE');
        $this->addSql('DROP TABLE project_association_profile_disciplines');
        $this->addSql('DROP TABLE project_association_profiles');
    }
}
