<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525212745 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Module Lives V1 : création des tables lives et live_attendees avec contrainte unique (live_id, user_id)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE live_attendees (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reminder_sent BOOLEAN DEFAULT false NOT NULL, live_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_72DE0B551DEBA901 ON live_attendees (live_id)');
        $this->addSql('CREATE INDEX IDX_72DE0B55A76ED395 ON live_attendees (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_live_attendee ON live_attendees (live_id, user_id)');
        $this->addSql('CREATE TABLE lives (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, external_url VARCHAR(500) NOT NULL, replay_url VARCHAR(500) DEFAULT NULL, cover_image_url VARCHAR(500) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, host_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D347E5E9092FFA4 ON lives (host_user_id)');
        $this->addSql('ALTER TABLE live_attendees ADD CONSTRAINT FK_72DE0B551DEBA901 FOREIGN KEY (live_id) REFERENCES lives (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE live_attendees ADD CONSTRAINT FK_72DE0B55A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lives ADD CONSTRAINT FK_5D347E5E9092FFA4 FOREIGN KEY (host_user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE live_attendees DROP CONSTRAINT FK_72DE0B551DEBA901');
        $this->addSql('ALTER TABLE live_attendees DROP CONSTRAINT FK_72DE0B55A76ED395');
        $this->addSql('ALTER TABLE lives DROP CONSTRAINT FK_5D347E5E9092FFA4');
        $this->addSql('DROP TABLE live_attendees');
        $this->addSql('DROP TABLE lives');
    }
}
