<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * ADR-0037 — Espace projets : gestion de projet interne de l'équipe Bazaart.
 *
 * 1. Crée les 12 tables du module (préfixe project_ / projects) :
 *    projects, project_tasks, project_task_assignees, project_task_labels,
 *    project_labels, project_subtasks, project_task_comments, project_notes,
 *    project_attachments, project_activities, project_member_profiles,
 *    project_drive_connections (jeton OAuth chiffré du Google Drive de l'équipe).
 *
 * 2. Donne l'accès à l'Espace projets (rôle ROLE_PROJECT) aux 3 membres de l'équipe
 *    DÉJÀ inscrites sur la plateforme. Les comptes absents sont créés ensuite avec
 *    la commande `php bin/console app:projets:acces --creer <email>` (cf. docs/espace-projets.md).
 *
 * 3. Crée quelques étiquettes de départ (Communication, Budget…) modifiables ensuite.
 *
 * Toutes les requêtes de données sont IDEMPOTENTES (rejouables sans effet de bord),
 * conformément à la convention du projet pour les migrations de données.
 */
final class Version20260924124344 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'ADR-0037 : tables de l\'Espace projets (projets, tâches, notes, Drive, activité) '
            . '+ accès ROLE_PROJECT pour les 3 membres de l\'équipe + étiquettes de départ.';
    }

    /** Emails des 3 membres de l'équipe qui accèdent à l'Espace projets (en minuscules). */
    private const array TEAM_EMAILS = [
        'mllebelamour@gmail.com',
        'zahibowendie@gmail.com',
        'g.charlesbel@gmail.com',
    ];

    public function up(Schema $schema): void
    {
        // ── 1. Schéma (généré par doctrine:migrations:diff) ───────────────────
        $this->addSql('CREATE TABLE project_activities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(40) NOT NULL, message VARCHAR(500) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT DEFAULT NULL, task_id INT DEFAULT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AD57D4D7166D1F9C ON project_activities (project_id)');
        $this->addSql('CREATE INDEX IDX_AD57D4D78DB60186 ON project_activities (task_id)');
        $this->addSql('CREATE INDEX IDX_AD57D4D710DAF24A ON project_activities (actor_id)');
        $this->addSql('CREATE INDEX idx_project_activities_created ON project_activities (created_at)');
        $this->addSql('CREATE TABLE project_attachments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source VARCHAR(20) NOT NULL, drive_file_id VARCHAR(128) DEFAULT NULL, name VARCHAR(255) NOT NULL, mime_type VARCHAR(150) DEFAULT NULL, url VARCHAR(1024) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT DEFAULT NULL, task_id INT DEFAULT NULL, added_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F0B0D2D166D1F9C ON project_attachments (project_id)');
        $this->addSql('CREATE INDEX IDX_8F0B0D2D8DB60186 ON project_attachments (task_id)');
        $this->addSql('CREATE INDEX IDX_8F0B0D2D55B127A4 ON project_attachments (added_by_id)');
        $this->addSql('CREATE TABLE project_drive_connections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_email VARCHAR(180) NOT NULL, encrypted_refresh_token TEXT NOT NULL, connected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, connected_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB4008FAB5CC298 ON project_drive_connections (connected_by_id)');
        $this->addSql('CREATE TABLE project_labels (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(40) NOT NULL, color VARCHAR(7) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A275E95B5E237E06 ON project_labels (name)');
        $this->addSql('CREATE TABLE project_member_profiles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, color VARCHAR(7) NOT NULL, tour_completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, checklist_dismissed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_view VARCHAR(20) DEFAULT NULL, email_notifications BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_44DC532AA76ED395 ON project_member_profiles (user_id)');
        $this->addSql('CREATE TABLE project_notes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) DEFAULT NULL, content TEXT NOT NULL, color VARCHAR(20) NOT NULL, pinned BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, author_id INT DEFAULT NULL, project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_124EAF12F675F31B ON project_notes (author_id)');
        $this->addSql('CREATE INDEX IDX_124EAF12166D1F9C ON project_notes (project_id)');
        $this->addSql('CREATE INDEX idx_project_notes_pinned_created ON project_notes (pinned, created_at)');
        $this->addSql('CREATE TABLE project_subtasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, done BOOLEAN DEFAULT false NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, task_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17A501968DB60186 ON project_subtasks (task_id)');
        $this->addSql('CREATE TABLE project_task_comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CBCFEB608DB60186 ON project_task_comments (task_id)');
        $this->addSql('CREATE INDEX IDX_CBCFEB60F675F31B ON project_task_comments (author_id)');
        $this->addSql('CREATE TABLE project_tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, priority VARCHAR(20) NOT NULL, start_date DATE DEFAULT NULL, due_date DATE DEFAULT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_430D6C09166D1F9C ON project_tasks (project_id)');
        $this->addSql('CREATE INDEX IDX_430D6C09B03A8386 ON project_tasks (created_by_id)');
        $this->addSql('CREATE INDEX idx_project_tasks_status ON project_tasks (status)');
        $this->addSql('CREATE INDEX idx_project_tasks_due_date ON project_tasks (due_date)');
        $this->addSql('CREATE TABLE project_task_assignees (task_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (task_id, user_id))');
        $this->addSql('CREATE INDEX IDX_8459E72F8DB60186 ON project_task_assignees (task_id)');
        $this->addSql('CREATE INDEX IDX_8459E72FA76ED395 ON project_task_assignees (user_id)');
        $this->addSql('CREATE TABLE project_task_labels (task_id INT NOT NULL, label_id INT NOT NULL, PRIMARY KEY (task_id, label_id))');
        $this->addSql('CREATE INDEX IDX_46B771398DB60186 ON project_task_labels (task_id)');
        $this->addSql('CREATE INDEX IDX_46B7713933B92F39 ON project_task_labels (label_id)');
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, color VARCHAR(7) DEFAULT \'#FFCB10\' NOT NULL, status VARCHAR(20) NOT NULL, priority VARCHAR(20) NOT NULL, start_date DATE DEFAULT NULL, due_date DATE DEFAULT NULL, drive_folder_id VARCHAR(128) DEFAULT NULL, drive_folder_name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C93B3A47E3C61F9 ON projects (owner_id)');
        $this->addSql('CREATE INDEX IDX_5C93B3A4B03A8386 ON projects (created_by_id)');
        $this->addSql('CREATE INDEX idx_projects_status ON projects (status)');
        $this->addSql('ALTER TABLE project_activities ADD CONSTRAINT FK_AD57D4D7166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_activities ADD CONSTRAINT FK_AD57D4D78DB60186 FOREIGN KEY (task_id) REFERENCES project_tasks (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_activities ADD CONSTRAINT FK_AD57D4D710DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_attachments ADD CONSTRAINT FK_8F0B0D2D166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_attachments ADD CONSTRAINT FK_8F0B0D2D8DB60186 FOREIGN KEY (task_id) REFERENCES project_tasks (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_attachments ADD CONSTRAINT FK_8F0B0D2D55B127A4 FOREIGN KEY (added_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_drive_connections ADD CONSTRAINT FK_AB4008FAB5CC298 FOREIGN KEY (connected_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_member_profiles ADD CONSTRAINT FK_44DC532AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_notes ADD CONSTRAINT FK_124EAF12F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_notes ADD CONSTRAINT FK_124EAF12166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_subtasks ADD CONSTRAINT FK_17A501968DB60186 FOREIGN KEY (task_id) REFERENCES project_tasks (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_task_comments ADD CONSTRAINT FK_CBCFEB608DB60186 FOREIGN KEY (task_id) REFERENCES project_tasks (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_task_comments ADD CONSTRAINT FK_CBCFEB60F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_tasks ADD CONSTRAINT FK_430D6C09166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_tasks ADD CONSTRAINT FK_430D6C09B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_task_assignees ADD CONSTRAINT FK_8459E72F8DB60186 FOREIGN KEY (task_id) REFERENCES project_tasks (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_task_assignees ADD CONSTRAINT FK_8459E72FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_task_labels ADD CONSTRAINT FK_46B771398DB60186 FOREIGN KEY (task_id) REFERENCES project_tasks (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_task_labels ADD CONSTRAINT FK_46B7713933B92F39 FOREIGN KEY (label_id) REFERENCES project_labels (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A47E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        // ── 2. Accès ROLE_PROJECT pour l'équipe ───────────────────────────────
        // users.roles est une colonne JSON : on la convertit en jsonb pour utiliser
        //   - `@>`  (« contient ») : ne rien faire si le rôle est déjà présent (idempotence)
        //   - `||`  (concaténation) : ajouter le rôle au tableau existant
        // puis on reconvertit en json. LOWER(email) : insensible à la casse
        // (« Mllebelamour@gmail.com » a été communiqué avec une majuscule).
        $emails = implode(', ', array_map(static fn (string $e): string => "'" . $e . "'", self::TEAM_EMAILS));
        $this->addSql(
            "UPDATE users SET roles = CAST(CAST(roles AS jsonb) || '[\"ROLE_PROJECT\"]'::jsonb AS json) "
            . "WHERE LOWER(email) IN (" . $emails . ") "
            . "AND NOT (CAST(roles AS jsonb) @> '[\"ROLE_PROJECT\"]'::jsonb)"
        );

        // ── 3. Étiquettes de départ ───────────────────────────────────────────
        // ON CONFLICT (name) DO NOTHING : rejouable sans doublon (index unique sur name).
        $this->addSql(
            "INSERT INTO project_labels (name, color) VALUES "
            . "('Communication', '#FF6B2C'), ('Budget', '#1F8A5B'), ('Partenaires', '#3B82F6'), "
            . "('Logistique', '#8B5CF6'), ('Administratif', '#5B584F'), ('Contenu', '#FFCB10') "
            . "ON CONFLICT (name) DO NOTHING"
        );
    }

    public function down(Schema $schema): void
    {
        // Retire ROLE_PROJECT de tous les comptes (l'opérateur jsonb `-` supprime
        // l'élément « ROLE_PROJECT » du tableau), puis supprime les tables.
        $this->addSql(
            "UPDATE users SET roles = CAST(CAST(roles AS jsonb) - 'ROLE_PROJECT' AS json) "
            . "WHERE CAST(roles AS jsonb) @> '[\"ROLE_PROJECT\"]'::jsonb"
        );

        $this->addSql('ALTER TABLE project_activities DROP CONSTRAINT FK_AD57D4D7166D1F9C');
        $this->addSql('ALTER TABLE project_activities DROP CONSTRAINT FK_AD57D4D78DB60186');
        $this->addSql('ALTER TABLE project_activities DROP CONSTRAINT FK_AD57D4D710DAF24A');
        $this->addSql('ALTER TABLE project_attachments DROP CONSTRAINT FK_8F0B0D2D166D1F9C');
        $this->addSql('ALTER TABLE project_attachments DROP CONSTRAINT FK_8F0B0D2D8DB60186');
        $this->addSql('ALTER TABLE project_attachments DROP CONSTRAINT FK_8F0B0D2D55B127A4');
        $this->addSql('ALTER TABLE project_drive_connections DROP CONSTRAINT FK_AB4008FAB5CC298');
        $this->addSql('ALTER TABLE project_member_profiles DROP CONSTRAINT FK_44DC532AA76ED395');
        $this->addSql('ALTER TABLE project_notes DROP CONSTRAINT FK_124EAF12F675F31B');
        $this->addSql('ALTER TABLE project_notes DROP CONSTRAINT FK_124EAF12166D1F9C');
        $this->addSql('ALTER TABLE project_subtasks DROP CONSTRAINT FK_17A501968DB60186');
        $this->addSql('ALTER TABLE project_task_comments DROP CONSTRAINT FK_CBCFEB608DB60186');
        $this->addSql('ALTER TABLE project_task_comments DROP CONSTRAINT FK_CBCFEB60F675F31B');
        $this->addSql('ALTER TABLE project_tasks DROP CONSTRAINT FK_430D6C09166D1F9C');
        $this->addSql('ALTER TABLE project_tasks DROP CONSTRAINT FK_430D6C09B03A8386');
        $this->addSql('ALTER TABLE project_task_assignees DROP CONSTRAINT FK_8459E72F8DB60186');
        $this->addSql('ALTER TABLE project_task_assignees DROP CONSTRAINT FK_8459E72FA76ED395');
        $this->addSql('ALTER TABLE project_task_labels DROP CONSTRAINT FK_46B771398DB60186');
        $this->addSql('ALTER TABLE project_task_labels DROP CONSTRAINT FK_46B7713933B92F39');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A47E3C61F9');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A4B03A8386');
        $this->addSql('DROP TABLE project_activities');
        $this->addSql('DROP TABLE project_attachments');
        $this->addSql('DROP TABLE project_drive_connections');
        $this->addSql('DROP TABLE project_labels');
        $this->addSql('DROP TABLE project_member_profiles');
        $this->addSql('DROP TABLE project_notes');
        $this->addSql('DROP TABLE project_subtasks');
        $this->addSql('DROP TABLE project_task_comments');
        $this->addSql('DROP TABLE project_tasks');
        $this->addSql('DROP TABLE project_task_assignees');
        $this->addSql('DROP TABLE project_task_labels');
        $this->addSql('DROP TABLE projects');
    }
}
