<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260526150555 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout table scraping_sources (sources BDD pilotables) + colonne disciplines dans scraped_resources';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        //
        // Note : les colonnes nb_items_dernier_run et statut_dernier_run ont des DEFAULT SQL
        // (0 et 'never_run') pour éviter une erreur PostgreSQL lors d'un INSERT sans ces valeurs.
        // Doctrine gère les valeurs PHP-side via les propriétés initialisées dans l'entité,
        // mais le DEFAULT SQL est indispensable si la table est alimentée hors Doctrine (ex: SQL direct).
        $this->addSql('CREATE TABLE scraping_sources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, url VARCHAR(500) NOT NULL, type VARCHAR(20) NOT NULL, scraper_slug VARCHAR(100) DEFAULT NULL, discipline_principale VARCHAR(200) DEFAULT NULL, pays_zone VARCHAR(100) DEFAULT NULL, actif BOOLEAN NOT NULL, derniere_execution TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, nb_items_dernier_run INT NOT NULL DEFAULT 0, statut_dernier_run VARCHAR(20) NOT NULL DEFAULT \'never_run\', message_erreur TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AAFABD16F47645AE ON scraping_sources (url)');
        $this->addSql('ALTER TABLE scraped_resources ADD disciplines VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE scraping_sources');
        $this->addSql('ALTER TABLE scraped_resources DROP disciplines');
    }
}
