<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Forum V1 — Images attachées et réactions emoji.
 *
 * 1. Colonne image_path (nullable) sur forum_threads et forum_replies :
 *    permet de joindre une image (JPEG/PNG/WebP/GIF, max 5 MB) à un sujet ou une réponse.
 *
 * 2. Nouvelle table forum_reactions : réactions emoji de style Slack/Discord
 *    (like, fire, bravo, heart, idea). Cible polymorphe simple : thread_id OU reply_id.
 *    Deux index UNIQUE empêchent qu'un même utilisateur pose deux fois le même type
 *    de réaction sur la même cible. NB : en PostgreSQL les NULL sont distincts, donc
 *    un index UNIQUE complet (user_id, thread_id, type) autorise plusieurs lignes où
 *    thread_id est NULL (les réactions sur réponses) — comportement voulu.
 *    FK ON DELETE CASCADE pour la cohérence (RGPD + suppression de thread/réponse).
 *
 * Migration générée par doctrine:migrations:diff (noms d'index/FK calculés par Doctrine
 * → garantit que doctrine:schema:validate reste satisfait).
 */
final class Version20260615235907 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Forum : images attachées (threads/replies) + table forum_reactions (réactions emoji)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE forum_reactions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, thread_id INT DEFAULT NULL, reply_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_63AFBE5A76ED395 ON forum_reactions (user_id)');
        $this->addSql('CREATE INDEX IDX_63AFBE5E2904019 ON forum_reactions (thread_id)');
        $this->addSql('CREATE INDEX IDX_63AFBE58A0E4E7F ON forum_reactions (reply_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_forum_reaction_user_thread_type ON forum_reactions (user_id, thread_id, type)');
        $this->addSql('CREATE UNIQUE INDEX uniq_forum_reaction_user_reply_type ON forum_reactions (user_id, reply_id, type)');
        $this->addSql('ALTER TABLE forum_reactions ADD CONSTRAINT FK_63AFBE5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_reactions ADD CONSTRAINT FK_63AFBE5E2904019 FOREIGN KEY (thread_id) REFERENCES forum_threads (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_reactions ADD CONSTRAINT FK_63AFBE58A0E4E7F FOREIGN KEY (reply_id) REFERENCES forum_replies (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_replies ADD image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE forum_threads ADD image_path VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE forum_reactions DROP CONSTRAINT FK_63AFBE5A76ED395');
        $this->addSql('ALTER TABLE forum_reactions DROP CONSTRAINT FK_63AFBE5E2904019');
        $this->addSql('ALTER TABLE forum_reactions DROP CONSTRAINT FK_63AFBE58A0E4E7F');
        $this->addSql('DROP TABLE forum_reactions');
        $this->addSql('ALTER TABLE forum_replies DROP image_path');
        $this->addSql('ALTER TABLE forum_threads DROP image_path');
    }
}
