<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * ADR-0038 — Espace projets : onglet « Opportunités pour nos associations ».
 *
 * Crée la table project_opportunity_reviews : décision de l'équipe (retenue,
 * candidature en cours, écartée) sur une opportunité du catalogue (resources),
 * avec l'association qui candidate et le projet de candidature créé.
 *
 * Une opportunité SANS ligne ici est « à étudier » : on ne stocke que les décisions.
 */
final class Version20260930140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'ADR-0038 : décisions de l\'équipe sur les opportunités des associations (project_opportunity_reviews).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE project_opportunity_reviews (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, association VARCHAR(20) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resource_id INT NOT NULL, project_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_19EF7C0389329D25 ON project_opportunity_reviews (resource_id)');
        $this->addSql('CREATE INDEX IDX_19EF7C03166D1F9C ON project_opportunity_reviews (project_id)');
        $this->addSql('CREATE INDEX IDX_19EF7C03896DBBDE ON project_opportunity_reviews (updated_by_id)');
        $this->addSql('ALTER TABLE project_opportunity_reviews ADD CONSTRAINT FK_19EF7C0389329D25 FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_opportunity_reviews ADD CONSTRAINT FK_19EF7C03166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_opportunity_reviews ADD CONSTRAINT FK_19EF7C03896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_opportunity_reviews DROP CONSTRAINT FK_19EF7C0389329D25');
        $this->addSql('ALTER TABLE project_opportunity_reviews DROP CONSTRAINT FK_19EF7C03166D1F9C');
        $this->addSql('ALTER TABLE project_opportunity_reviews DROP CONSTRAINT FK_19EF7C03896DBBDE');
        $this->addSql('DROP TABLE project_opportunity_reviews');
    }
}
