<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260523134925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table notifications avec ses index (système de notifications in-app V1).';
    }

    public function up(Schema $schema): void
    {
        // Création de la table notifications uniquement.
        // Les tables conversations, conversation_participants et messages existent déjà
        // (créées lors d'une migration précédente du module messagerie).
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, related_entity_type VARCHAR(50) DEFAULT NULL, related_entity_id INT DEFAULT NULL, data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        // Index simple sur recipient_id (créé par Doctrine pour la FK)
        $this->addSql('CREATE INDEX IDX_6000B0D3E92F8F78 ON notifications (recipient_id)');
        // Index composite (recipient_id, is_read) → optimise countUnreadByUser() et findUnreadByUser()
        $this->addSql('CREATE INDEX idx_notifications_recipient_read ON notifications (recipient_id, is_read)');
        // Index sur created_at → optimise les tris chronologiques dans findRecentByUser()
        $this->addSql('CREATE INDEX idx_notifications_created_at ON notifications (created_at)');
        // Clé étrangère vers users avec ON DELETE CASCADE :
        // si un user est supprimé, toutes ses notifications le sont aussi automatiquement
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3E92F8F78 FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // Suppression de la contrainte FK avant la table (obligation PostgreSQL)
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3E92F8F78');
        $this->addSql('DROP TABLE notifications');
    }
}
