<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration : Création de la table match_consultations (ADR-0022 Lot D - Paywall freemium).
 *
 * Cette table enregistre chaque consultation d'une carte de matching par un utilisateur gratuit.
 * Elle permet de limiter les utilisateurs non abonnés à 3 consultations par semaine ISO
 * (fenêtre lundi–dimanche UTC).
 *
 * Index créés :
 *   - idx_match_consultations_user_date : composite (user_id, viewed_at) pour le COUNT hebdomadaire
 *   - IDX_5E7252CAA76ED395 : user_id (auto Doctrine FK)
 *   - IDX_5E7252CA89329D25 : resource_id (auto Doctrine FK)
 */
final class Version20260620012106 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création de match_consultations pour le paywall freemium (ADR-0022 Lot D) : limite de 3 consultations de matchs par semaine pour les utilisateurs gratuits.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE match_consultations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, viewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, resource_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E7252CAA76ED395 ON match_consultations (user_id)');
        $this->addSql('CREATE INDEX IDX_5E7252CA89329D25 ON match_consultations (resource_id)');
        $this->addSql('CREATE INDEX idx_match_consultations_user_date ON match_consultations (user_id, viewed_at)');
        $this->addSql('ALTER TABLE match_consultations ADD CONSTRAINT FK_5E7252CAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE match_consultations ADD CONSTRAINT FK_5E7252CA89329D25 FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE match_consultations DROP CONSTRAINT FK_5E7252CAA76ED395');
        $this->addSql('ALTER TABLE match_consultations DROP CONSTRAINT FK_5E7252CA89329D25');
        $this->addSql('DROP TABLE match_consultations');
    }
}
