<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260307214957 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE organization_profiles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, siret VARCHAR(14) DEFAULT NULL, description TEXT DEFAULT NULL, website_url VARCHAR(255) DEFAULT NULL, contact_email VARCHAR(180) DEFAULT NULL, location VARCHAR(150) DEFAULT NULL, logo_path VARCHAR(255) DEFAULT NULL, is_verified BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64284792A76ED395 ON organization_profiles (user_id)');
        $this->addSql('ALTER TABLE organization_profiles ADD CONSTRAINT FK_64284792A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE organization_profiles DROP CONSTRAINT FK_64284792A76ED395');
        $this->addSql('DROP TABLE organization_profiles');
    }
}
