<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260523041548 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE resource_alerts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notify_on_new_resource BOOLEAN DEFAULT true NOT NULL, frequency VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F862A91A76ED395 ON resource_alerts (user_id)');
        $this->addSql('CREATE TABLE resource_alert_disciplines (resource_alert_id INT NOT NULL, discipline_id INT NOT NULL, PRIMARY KEY (resource_alert_id, discipline_id))');
        $this->addSql('CREATE INDEX IDX_B9624F383D8F95DF ON resource_alert_disciplines (resource_alert_id)');
        $this->addSql('CREATE INDEX IDX_B9624F38A5522701 ON resource_alert_disciplines (discipline_id)');
        $this->addSql('CREATE TABLE resource_alert_resource_types (resource_alert_id INT NOT NULL, resource_type_id INT NOT NULL, PRIMARY KEY (resource_alert_id, resource_type_id))');
        $this->addSql('CREATE INDEX IDX_7A3C0E893D8F95DF ON resource_alert_resource_types (resource_alert_id)');
        $this->addSql('CREATE INDEX IDX_7A3C0E8998EC6B7B ON resource_alert_resource_types (resource_type_id)');
        $this->addSql('CREATE TABLE resource_favorites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, resource_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4CA0336AA76ED395 ON resource_favorites (user_id)');
        $this->addSql('CREATE INDEX IDX_4CA0336A89329D25 ON resource_favorites (resource_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_resource_favorite ON resource_favorites (user_id, resource_id)');
        $this->addSql('ALTER TABLE resource_alerts ADD CONSTRAINT FK_3F862A91A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resource_alert_disciplines ADD CONSTRAINT FK_B9624F383D8F95DF FOREIGN KEY (resource_alert_id) REFERENCES resource_alerts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resource_alert_disciplines ADD CONSTRAINT FK_B9624F38A5522701 FOREIGN KEY (discipline_id) REFERENCES disciplines (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resource_alert_resource_types ADD CONSTRAINT FK_7A3C0E893D8F95DF FOREIGN KEY (resource_alert_id) REFERENCES resource_alerts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resource_alert_resource_types ADD CONSTRAINT FK_7A3C0E8998EC6B7B FOREIGN KEY (resource_type_id) REFERENCES resource_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resource_favorites ADD CONSTRAINT FK_4CA0336AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resource_favorites ADD CONSTRAINT FK_4CA0336A89329D25 FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resource_alerts DROP CONSTRAINT FK_3F862A91A76ED395');
        $this->addSql('ALTER TABLE resource_alert_disciplines DROP CONSTRAINT FK_B9624F383D8F95DF');
        $this->addSql('ALTER TABLE resource_alert_disciplines DROP CONSTRAINT FK_B9624F38A5522701');
        $this->addSql('ALTER TABLE resource_alert_resource_types DROP CONSTRAINT FK_7A3C0E893D8F95DF');
        $this->addSql('ALTER TABLE resource_alert_resource_types DROP CONSTRAINT FK_7A3C0E8998EC6B7B');
        $this->addSql('ALTER TABLE resource_favorites DROP CONSTRAINT FK_4CA0336AA76ED395');
        $this->addSql('ALTER TABLE resource_favorites DROP CONSTRAINT FK_4CA0336A89329D25');
        $this->addSql('DROP TABLE resource_alerts');
        $this->addSql('DROP TABLE resource_alert_disciplines');
        $this->addSql('DROP TABLE resource_alert_resource_types');
        $this->addSql('DROP TABLE resource_favorites');
    }
}
