<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration du module Formation (CDC V3 §5.7).
 *
 * Crée les 6 tables nécessaires à la gestion des formations en ligne :
 *
 *   courses               → La formation (catalogue, description, formateur)
 *   course_modules        → Modules (chapitres) d'une formation
 *   lessons               → Leçons individuelles (vidéo Bunny Stream ou iframe)
 *   lesson_resources      → Fichiers téléchargeables attachés à une leçon
 *   course_enrollments    → Inscriptions utilisateurs × formations
 *   lesson_progresses     → Suivi de la progression par leçon
 *
 * La table course_enrollments a une contrainte UNIQUE sur (user_id, course_id)
 * pour garantir qu'un utilisateur ne peut s'inscrire qu'une seule fois.
 *
 * Toutes les FK ont un ON DELETE explicite :
 *   - CASCADE  → suppression cohérente des données liées (orphelins impossibles)
 *   - SET NULL → préservation de la donnée sans sa référence (non utilisé ici)
 *
 * La colonne `level` de courses utilise l'enum CourseLevel comme type VARCHAR(20).
 * PostgreSQL ne requiert pas de CREATE TYPE ENUM — on utilise un VARCHAR simple
 * et Doctrine s'occupe du mapping avec l'enum PHP.
 */
final class Version20260525100937 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée les 6 tables du module Formation : courses, course_modules, lessons, lesson_resources, course_enrollments, lesson_progresses.';
    }

    public function up(Schema $schema): void
    {
        // ─── Table courses ────────────────────────────────────────────────────
        // Table principale : une formation avec ses métadonnées.
        // is_published (default false) : brouillon jusqu'à publication explicite par un admin.
        // level (VARCHAR 20) : valeurs possibles 'beginner', 'intermediate', 'advanced'
        //                      — mappé côté PHP vers l'enum CourseLevel.
        $this->addSql(<<<'SQL'
            CREATE TABLE courses (
                id               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                slug             VARCHAR(255) NOT NULL,
                title            VARCHAR(255) NOT NULL,
                subtitle         VARCHAR(255)          DEFAULT NULL,
                description      TEXT                  DEFAULT NULL,
                cover_image      VARCHAR(255)          DEFAULT NULL,
                trailer_video_url VARCHAR(500)         DEFAULT NULL,
                instructor_name  VARCHAR(255)          DEFAULT NULL,
                instructor_bio   TEXT                  DEFAULT NULL,
                instructor_avatar VARCHAR(255)         DEFAULT NULL,
                duration_minutes_total INT             DEFAULT NULL,
                level            VARCHAR(20)  NOT NULL DEFAULT 'beginner',
                is_published     BOOLEAN      NOT NULL DEFAULT false,
                published_at     TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at       TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at       TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        // Contrainte UNIQUE sur slug : base de la route /formations/{slug}
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A9185589989D9B62 ON courses (slug)');

        // ─── Table course_modules ─────────────────────────────────────────────
        // Un module (chapitre) appartient à une formation.
        // order_position (default 0) : détermine l'ordre d'affichage dans la formation.
        $this->addSql(<<<'SQL'
            CREATE TABLE course_modules (
                id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                course_id      INT         NOT NULL,
                title          VARCHAR(255) NOT NULL,
                description    TEXT         DEFAULT NULL,
                order_position INT         NOT NULL DEFAULT 0,
                PRIMARY KEY (id)
            )
        SQL);
        // Index sur course_id pour accélérer la récupération des modules d'une formation
        $this->addSql('CREATE INDEX IDX_D0C0E4C591CC992 ON course_modules (course_id)');
        // FK vers courses — CASCADE : supprimer une formation supprime ses modules
        $this->addSql('ALTER TABLE course_modules ADD CONSTRAINT FK_D0C0E4C591CC992 FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE NOT DEFERRABLE');

        // ─── Table lessons ────────────────────────────────────────────────────
        // Une leçon appartient à un module. Contient la vidéo et les métadonnées.
        // video_bunny_id : identifiant Bunny Stream pour le player avec token signé
        // video_url      : URL iframe générique (YouTube, Vimeo, fallback)
        // is_free_preview (default false) : accessible sans inscription si true
        $this->addSql(<<<'SQL'
            CREATE TABLE lessons (
                id               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                module_id        INT          NOT NULL,
                title            VARCHAR(255) NOT NULL,
                description      TEXT         DEFAULT NULL,
                video_bunny_id   VARCHAR(255) DEFAULT NULL,
                video_url        VARCHAR(500) DEFAULT NULL,
                duration_seconds INT          DEFAULT NULL,
                order_position   INT         NOT NULL DEFAULT 0,
                is_free_preview  BOOLEAN     NOT NULL DEFAULT false,
                PRIMARY KEY (id)
            )
        SQL);
        // Index sur module_id pour les requêtes "leçons d'un module"
        $this->addSql('CREATE INDEX IDX_3F4218D9AFC2B591 ON lessons (module_id)');
        // FK vers course_modules — CASCADE : supprimer un module supprime ses leçons
        $this->addSql('ALTER TABLE lessons ADD CONSTRAINT FK_3F4218D9AFC2B591 FOREIGN KEY (module_id) REFERENCES course_modules (id) ON DELETE CASCADE NOT DEFERRABLE');

        // ─── Table lesson_resources ───────────────────────────────────────────
        // Fichiers téléchargeables attachés à une leçon (PDFs, partitions...).
        // file_path (VARCHAR 500) : chemin relatif dans /uploads/
        $this->addSql(<<<'SQL'
            CREATE TABLE lesson_resources (
                id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                lesson_id INT          NOT NULL,
                title     VARCHAR(255) NOT NULL,
                file_path VARCHAR(500) NOT NULL,
                file_size INT          DEFAULT NULL,
                mime_type VARCHAR(100) DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        // Index sur lesson_id pour les requêtes "ressources d'une leçon"
        $this->addSql('CREATE INDEX IDX_AB9E0E5BCDF80196 ON lesson_resources (lesson_id)');
        // FK vers lessons — CASCADE : supprimer une leçon supprime ses ressources
        $this->addSql('ALTER TABLE lesson_resources ADD CONSTRAINT FK_AB9E0E5BCDF80196 FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE NOT DEFERRABLE');

        // ─── Table course_enrollments ─────────────────────────────────────────
        // Inscriptions utilisateurs × formations.
        // progress_percent (0–100) : mis à jour par CourseEnrollmentService::recalculateProgress()
        // enrolled_at : initialisé par ORM\PrePersist au moment de l'inscription
        $this->addSql(<<<'SQL'
            CREATE TABLE course_enrollments (
                id               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id          INT     NOT NULL,
                course_id        INT     NOT NULL,
                enrolled_at      TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                completed_at     TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                progress_percent INT     NOT NULL DEFAULT 0,
                PRIMARY KEY (id)
            )
        SQL);
        // Index sur user_id pour "mes formations"
        $this->addSql('CREATE INDEX IDX_97B31E6AA76ED395 ON course_enrollments (user_id)');
        // Index sur course_id pour "inscrits à cette formation" (dashboard admin)
        $this->addSql('CREATE INDEX IDX_97B31E6A591CC992 ON course_enrollments (course_id)');
        // Contrainte UNIQUE : un utilisateur ne peut s'inscrire qu'une fois par formation
        // Correspond à #[ORM\UniqueConstraint(name: 'unique_enrollment', columns: ['user_id', 'course_id'])]
        $this->addSql('CREATE UNIQUE INDEX unique_enrollment ON course_enrollments (user_id, course_id)');
        // FK vers users — CASCADE RGPD : supprimer un compte supprime ses inscriptions
        $this->addSql('ALTER TABLE course_enrollments ADD CONSTRAINT FK_97B31E6AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        // FK vers courses — CASCADE : supprimer une formation supprime les inscriptions
        $this->addSql('ALTER TABLE course_enrollments ADD CONSTRAINT FK_97B31E6A591CC992 FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE NOT DEFERRABLE');

        // ─── Table lesson_progresses ──────────────────────────────────────────
        // Suivi de progression par leçon pour chaque inscription.
        // last_position_seconds : position de reprise dans la vidéo (AJAX périodique)
        // completed_at : null = non terminée, sinon = date de complétion
        $this->addSql(<<<'SQL'
            CREATE TABLE lesson_progresses (
                id                    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                enrollment_id         INT NOT NULL,
                lesson_id             INT NOT NULL,
                started_at            TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                completed_at          TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                last_position_seconds INT NOT NULL DEFAULT 0,
                PRIMARY KEY (id)
            )
        SQL);
        // Index sur enrollment_id pour "progressions d'une inscription"
        $this->addSql('CREATE INDEX IDX_3F12F21AADB5C28 ON lesson_progresses (enrollment_id)');
        // Index sur lesson_id pour les requêtes depuis Lesson::$progresses
        $this->addSql('CREATE INDEX IDX_3F12F21ACDF80196 ON lesson_progresses (lesson_id)');
        // FK vers course_enrollments — CASCADE : supprimer une inscription supprime ses progressions
        $this->addSql('ALTER TABLE lesson_progresses ADD CONSTRAINT FK_3F12F21AADB5C28 FOREIGN KEY (enrollment_id) REFERENCES course_enrollments (id) ON DELETE CASCADE NOT DEFERRABLE');
        // FK vers lessons — CASCADE : supprimer une leçon supprime sa progression
        $this->addSql('ALTER TABLE lesson_progresses ADD CONSTRAINT FK_3F12F21ACDF80196 FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // Suppression dans l'ordre inverse des dépendances pour respecter les FK.
        // PostgreSQL interdit de supprimer une table référencée par une FK active.

        // 1. Supprimer les FK avant les tables pour éviter les erreurs de contrainte
        $this->addSql('ALTER TABLE lesson_progresses DROP CONSTRAINT FK_3F12F21AADB5C28');
        $this->addSql('ALTER TABLE lesson_progresses DROP CONSTRAINT FK_3F12F21ACDF80196');
        $this->addSql('ALTER TABLE course_enrollments DROP CONSTRAINT FK_97B31E6AA76ED395');
        $this->addSql('ALTER TABLE course_enrollments DROP CONSTRAINT FK_97B31E6A591CC992');
        $this->addSql('ALTER TABLE lesson_resources DROP CONSTRAINT FK_AB9E0E5BCDF80196');
        $this->addSql('ALTER TABLE lessons DROP CONSTRAINT FK_3F4218D9AFC2B591');
        $this->addSql('ALTER TABLE course_modules DROP CONSTRAINT FK_D0C0E4C591CC992');

        // 2. Supprimer les tables feuilles en premier, puis les tables parentes
        $this->addSql('DROP TABLE lesson_progresses');
        $this->addSql('DROP TABLE course_enrollments');
        $this->addSql('DROP TABLE lesson_resources');
        $this->addSql('DROP TABLE lessons');
        $this->addSql('DROP TABLE course_modules');
        $this->addSql('DROP TABLE courses');
    }
}
