<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260430170531 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE scraped_resources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, url VARCHAR(500) DEFAULT NULL, type VARCHAR(100) DEFAULT NULL, source_site VARCHAR(100) DEFAULT NULL, deadline VARCHAR(150) DEFAULT NULL, relevance_score INT NOT NULL, documents TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, scraped_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FA38F8BEF47645AE ON scraped_resources (url)');
        $this->addSql('ALTER TABLE resources ALTER organization_id DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE scraped_resources');
        $this->addSql('ALTER TABLE resources ALTER organization_id SET NOT NULL');
    }
}
