<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260307201004 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE artist_profiles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, display_name VARCHAR(100) NOT NULL, bio TEXT DEFAULT NULL, location VARCHAR(150) DEFAULT NULL, website_url VARCHAR(255) DEFAULT NULL, portfolio_url VARCHAR(255) DEFAULT NULL, social_links JSON DEFAULT NULL, avatar_path VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_333A6F61A76ED395 ON artist_profiles (user_id)');
        $this->addSql('ALTER TABLE artist_profiles ADD CONSTRAINT FK_333A6F61A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE artist_profiles DROP CONSTRAINT FK_333A6F61A76ED395');
        $this->addSql('DROP TABLE artist_profiles');
    }
}
