<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260523131534 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création des tables forum_categories, forum_threads et forum_replies pour le module Forum communautaire Bazaart.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE forum_categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, description VARCHAR(500) DEFAULT NULL, icon VARCHAR(50) DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, order_position INT DEFAULT 0 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B8C5FB2D989D9B62 ON forum_categories (slug)');
        $this->addSql('CREATE TABLE forum_replies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, is_solution BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, thread_id INT NOT NULL, author_id INT NOT NULL, parent_reply_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_51CC2A5BE2904019 ON forum_replies (thread_id)');
        $this->addSql('CREATE INDEX IDX_51CC2A5BF675F31B ON forum_replies (author_id)');
        $this->addSql('CREATE INDEX IDX_51CC2A5B15C3E2AE ON forum_replies (parent_reply_id)');
        $this->addSql('CREATE TABLE forum_threads (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(280) NOT NULL, content TEXT NOT NULL, is_pinned BOOLEAN DEFAULT false NOT NULL, is_locked BOOLEAN DEFAULT false NOT NULL, views_count INT DEFAULT 0 NOT NULL, replies_count INT DEFAULT 0 NOT NULL, last_reply_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9E4270AC989D9B62 ON forum_threads (slug)');
        $this->addSql('CREATE INDEX IDX_9E4270AC12469DE2 ON forum_threads (category_id)');
        $this->addSql('CREATE INDEX IDX_9E4270ACF675F31B ON forum_threads (author_id)');
        $this->addSql('ALTER TABLE forum_replies ADD CONSTRAINT FK_51CC2A5BE2904019 FOREIGN KEY (thread_id) REFERENCES forum_threads (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_replies ADD CONSTRAINT FK_51CC2A5BF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_replies ADD CONSTRAINT FK_51CC2A5B15C3E2AE FOREIGN KEY (parent_reply_id) REFERENCES forum_replies (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_threads ADD CONSTRAINT FK_9E4270AC12469DE2 FOREIGN KEY (category_id) REFERENCES forum_categories (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_threads ADD CONSTRAINT FK_9E4270ACF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE forum_replies DROP CONSTRAINT FK_51CC2A5BE2904019');
        $this->addSql('ALTER TABLE forum_replies DROP CONSTRAINT FK_51CC2A5BF675F31B');
        $this->addSql('ALTER TABLE forum_replies DROP CONSTRAINT FK_51CC2A5B15C3E2AE');
        $this->addSql('ALTER TABLE forum_threads DROP CONSTRAINT FK_9E4270AC12469DE2');
        $this->addSql('ALTER TABLE forum_threads DROP CONSTRAINT FK_9E4270ACF675F31B');
        $this->addSql('DROP TABLE forum_categories');
        $this->addSql('DROP TABLE forum_replies');
        $this->addSql('DROP TABLE forum_threads');
    }
}
