<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration Stripe V1 — Intégration des paiements.
 *
 * Modifications :
 *   1. Table `courses` : ajout de 3 colonnes pour la tarification Stripe
 *      - price_in_cents     : prix en centimes (null = gratuit)
 *      - stripe_product_id  : ID du Product Stripe (prod_xxx)
 *      - stripe_price_id    : ID du Price Stripe actif (price_xxx)
 *
 *   2. Nouvelle table `subscriptions` : abonnements récurrents des utilisateurs
 *      Liée à `users` via FK + cascade suppression (RGPD).
 *      Index sur user_id et stripe_subscription_id pour les lookups fréquents.
 *
 *   3. Nouvelle table `course_payments` : paiements uniques pour l'accès aux formations
 *      Liée à `users` et `courses` via FK.
 *      Contrainte UNIQUE sur stripe_payment_intent_id (idempotence webhooks).
 *      Index composite (user_id, course_id) pour la vérification d'accès.
 */
final class Version20260615211300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Intégration Stripe : colonnes prix sur courses, table subscriptions, table course_payments';
    }

    public function up(Schema $schema): void
    {
        // ── 1. Ajout des colonnes Stripe sur la table courses ─────────────────
        //
        // Ces colonnes sont nullable car les formations existantes n'ont pas
        // encore de prix défini. L'admin les renseigne via l'interface d'édition.

        // Prix de la formation en centimes d'euro (ex : 2900 = 29,00€)
        // Nullable → formation gratuite ou prix non encore défini
        $this->addSql('ALTER TABLE courses ADD COLUMN IF NOT EXISTS price_in_cents INT DEFAULT NULL');

        // ID du Product Stripe associé à cette formation (prod_xxx)
        // Créé par StripeService::createOrUpdateCourseProduct()
        $this->addSql('ALTER TABLE courses ADD COLUMN IF NOT EXISTS stripe_product_id VARCHAR(255) DEFAULT NULL');

        // ID du Price Stripe actif pour cette formation (price_xxx)
        // Recréé si le prix change (un Price Stripe est immuable)
        $this->addSql('ALTER TABLE courses ADD COLUMN IF NOT EXISTS stripe_price_id VARCHAR(255) DEFAULT NULL');

        // ── 2. Création de la table subscriptions ─────────────────────────────
        //
        // Stocke les abonnements récurrents (mensuel / annuel) des utilisateurs.
        // Synchronisée avec Stripe via les webhooks customer.subscription.*.
        // Un utilisateur peut avoir plusieurs lignes (historique), mais une seule
        // avec status='active' à la fois (contrainte portée par la logique métier).
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS subscriptions (
                id               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id          INT NOT NULL,
                stripe_subscription_id VARCHAR(255) NOT NULL,
                stripe_customer_id     VARCHAR(255) NOT NULL,
                plan             VARCHAR(20) NOT NULL,
                status           VARCHAR(50) NOT NULL,
                current_period_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                canceled_at      TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at       TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at       TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        // Clé étrangère vers users — CASCADE pour respecter le RGPD (suppression compte)
        $this->addSql('ALTER TABLE subscriptions ADD CONSTRAINT FK_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Index pour les lookups fréquents
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON subscriptions (user_id)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_subscriptions_stripe_id ON subscriptions (stripe_subscription_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe_id ON subscriptions (stripe_subscription_id)');

        // ── 3. Création de la table course_payments ───────────────────────────
        //
        // Trace les paiements uniques pour l'accès aux formations payantes.
        // Créée par le webhook checkout.session.completed (mode=payment).
        // La présence d'un enregistrement avec status='completed' = preuve d'achat.
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS course_payments (
                id                          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id                     INT NOT NULL,
                course_id                   INT NOT NULL,
                stripe_payment_intent_id    VARCHAR(255) DEFAULT NULL,
                stripe_checkout_session_id  VARCHAR(255) DEFAULT NULL,
                amount_in_cents             INT NOT NULL,
                status                      VARCHAR(50) NOT NULL,
                created_at                  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        // Clé étrangère vers users — CASCADE pour RGPD
        $this->addSql('ALTER TABLE course_payments ADD CONSTRAINT FK_course_payments_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Clé étrangère vers courses — CASCADE si la formation est supprimée
        $this->addSql('ALTER TABLE course_payments ADD CONSTRAINT FK_course_payments_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Contrainte UNIQUE sur stripe_payment_intent_id pour l'idempotence des webhooks
        // (null est autorisé plusieurs fois dans un index UNIQUE sous PostgreSQL)
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_course_payments_payment_intent ON course_payments (stripe_payment_intent_id)');

        // Index composite pour la vérification rapide "utilisateur a-t-il acheté cette formation ?"
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_course_payments_user_course ON course_payments (user_id, course_id)');
    }

    public function down(Schema $schema): void
    {
        // ── Suppression dans l'ordre inverse (contraintes FK d'abord) ─────────

        // Suppression de course_payments
        $this->addSql('ALTER TABLE course_payments DROP CONSTRAINT IF EXISTS FK_course_payments_user');
        $this->addSql('ALTER TABLE course_payments DROP CONSTRAINT IF EXISTS FK_course_payments_course');
        $this->addSql('DROP TABLE IF EXISTS course_payments');

        // Suppression de subscriptions
        $this->addSql('ALTER TABLE subscriptions DROP CONSTRAINT IF EXISTS FK_subscriptions_user');
        $this->addSql('DROP TABLE IF EXISTS subscriptions');

        // Suppression des colonnes Stripe sur courses
        $this->addSql('ALTER TABLE courses DROP COLUMN IF EXISTS price_in_cents');
        $this->addSql('ALTER TABLE courses DROP COLUMN IF EXISTS stripe_product_id');
        $this->addSql('ALTER TABLE courses DROP COLUMN IF EXISTS stripe_price_id');
    }
}
