<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260308093450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE disciplines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD1D5CD85E237E06 ON disciplines (name)');
        $this->addSql('CREATE TABLE resource_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_728BF3025E237E06 ON resource_types (name)');
        $this->addSql('CREATE TABLE resources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, external_url VARCHAR(500) DEFAULT NULL, deadline DATE DEFAULT NULL, location VARCHAR(150) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resource_type_id INT NOT NULL, organization_id INT NOT NULL, submitted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF66EBAE98EC6B7B ON resources (resource_type_id)');
        $this->addSql('CREATE INDEX IDX_EF66EBAE32C8A3DE ON resources (organization_id)');
        $this->addSql('CREATE INDEX IDX_EF66EBAE79F7D87D ON resources (submitted_by_id)');
        $this->addSql('CREATE TABLE resource_disciplines (resource_id INT NOT NULL, discipline_id INT NOT NULL, PRIMARY KEY (resource_id, discipline_id))');
        $this->addSql('CREATE INDEX IDX_A9A6628A89329D25 ON resource_disciplines (resource_id)');
        $this->addSql('CREATE INDEX IDX_A9A6628AA5522701 ON resource_disciplines (discipline_id)');
        $this->addSql('ALTER TABLE resources ADD CONSTRAINT FK_EF66EBAE98EC6B7B FOREIGN KEY (resource_type_id) REFERENCES resource_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resources ADD CONSTRAINT FK_EF66EBAE32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization_profiles (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resources ADD CONSTRAINT FK_EF66EBAE79F7D87D FOREIGN KEY (submitted_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resource_disciplines ADD CONSTRAINT FK_A9A6628A89329D25 FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resource_disciplines ADD CONSTRAINT FK_A9A6628AA5522701 FOREIGN KEY (discipline_id) REFERENCES disciplines (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resources DROP CONSTRAINT FK_EF66EBAE98EC6B7B');
        $this->addSql('ALTER TABLE resources DROP CONSTRAINT FK_EF66EBAE32C8A3DE');
        $this->addSql('ALTER TABLE resources DROP CONSTRAINT FK_EF66EBAE79F7D87D');
        $this->addSql('ALTER TABLE resource_disciplines DROP CONSTRAINT FK_A9A6628A89329D25');
        $this->addSql('ALTER TABLE resource_disciplines DROP CONSTRAINT FK_A9A6628AA5522701');
        $this->addSql('DROP TABLE disciplines');
        $this->addSql('DROP TABLE resource_types');
        $this->addSql('DROP TABLE resources');
        $this->addSql('DROP TABLE resource_disciplines');
    }
}
