<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260526030315 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création de la table app_settings pour les paramètres applicatifs configurables depuis l\'admin (clé API Anthropic, activation scraping, etc.)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting_key VARCHAR(100) NOT NULL, setting_value TEXT DEFAULT NULL, is_secret BOOLEAN NOT NULL, label VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EDC5C0685FA1E697 ON app_settings (setting_key)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE app_settings');
    }
}
