<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Propositions de formation par les membres (ADR-0012, Option B).
 *
 * Nouvelle table course_proposals : un membre soumet une idée de formation
 * (titre, description, public visé, expérience, niveau optionnel, lien portfolio).
 * Un admin l'accepte ou la refuse (status + admin_note + reviewed_by/at).
 * FK proposed_by ON DELETE CASCADE (RGPD) ; reviewed_by ON DELETE SET NULL.
 */
final class Version20260616020224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table course_proposals (propositions de formation par les membres)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE course_proposals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, target_audience TEXT NOT NULL, experience TEXT NOT NULL, level VARCHAR(20) DEFAULT NULL, portfolio_url VARCHAR(500) DEFAULT NULL, status VARCHAR(20) NOT NULL, admin_note TEXT DEFAULT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, proposed_by_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_271B7A23DAB5A938 ON course_proposals (proposed_by_id)');
        $this->addSql('CREATE INDEX IDX_271B7A23FC6B21F1 ON course_proposals (reviewed_by_id)');
        $this->addSql('ALTER TABLE course_proposals ADD CONSTRAINT FK_271B7A23DAB5A938 FOREIGN KEY (proposed_by_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_proposals ADD CONSTRAINT FK_271B7A23FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE course_proposals DROP CONSTRAINT FK_271B7A23DAB5A938');
        $this->addSql('ALTER TABLE course_proposals DROP CONSTRAINT FK_271B7A23FC6B21F1');
        $this->addSql('DROP TABLE course_proposals');
    }
}
